"use client";

import Link from "next/link";
import { ArrowUpRight, CheckCircle2, MessageCircle, Play, Send } from "lucide-react";
import { FaInstagram, FaLinkedinIn, FaYoutube } from "react-icons/fa";
import { useState } from "react";

const channels = [
  { name: "Instagram", handle: "@iqrainstitute", text: "Daily study motivation, campus moments & student wins.", Icon: FaInstagram, tone: "from-fuchsia-500 to-orange-400" },
  { name: "YouTube", handle: "Iqra Institute", text: "Guides, class snippets, and useful language tips.", Icon: FaYoutube, tone: "from-red-600 to-rose-400" },
  { name: "LinkedIn", handle: "Iqra Language Institute", text: "News, opportunities, and professional learning.", Icon: FaLinkedinIn, tone: "from-sky-700 to-blue-500" },
];

export default function SocialMediaPage() {
 const [sent, setSent] = useState(false);
 return <main className="min-h-screen bg-[#071a32] text-white"><section className="relative overflow-hidden px-6 pb-16 pt-10 sm:px-10 lg:px-16 lg:pb-24"><div className="absolute -right-32 top-10 h-96 w-96 rounded-full bg-[#ff4f6d]/20 blur-3xl"/><div className="absolute -left-24 bottom-0 h-64 w-64 rounded-full bg-cyan-400/15 blur-3xl"/><div className="relative mx-auto max-w-7xl"><Link href="/" className="font-bold text-cyan-300">← Iqra Institute</Link><div className="mt-16 grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="font-bold uppercase tracking-[.22em] text-[#ff7189]">Our community</p><h1 className="mt-4 text-5xl font-black leading-none tracking-tight sm:text-7xl">Keep learning<br /><span className="text-cyan-300">in your feed.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Practical tips, inspiring learner stories, and a little daily momentum—wherever you are.</p></div><div className="rounded-[2rem] border border-white/15 bg-white/10 p-7 backdrop-blur"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#ff4f6d]"><MessageCircle /></div><div><p className="font-extrabold">Join the conversation</p><p className="text-sm text-slate-300">Tips worth saving. People worth knowing.</p></div></div><div className="mt-7 grid grid-cols-3 gap-3">{['Language tips', 'Student stories', 'Campus life'].map((x) => <div key={x} className="rounded-xl bg-white/10 p-3 text-center text-xs font-bold text-slate-200">{x}</div>)}</div></div></div></div></section>
 <section className="bg-[#f7f9fc] px-6 py-16 text-slate-900 sm:px-10 lg:px-16"><div className="mx-auto max-w-7xl"><div className="mb-9"><p className="font-bold uppercase tracking-[.18em] text-[#0b7295]">Choose your corner</p><h2 className="mt-2 text-4xl font-black">Find us where you scroll.</h2></div><div className="grid gap-6 lg:grid-cols-3">{channels.map(({name,handle,text,Icon,tone}) => <a key={name} href="#" className="group rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-2 hover:shadow-xl"><div className={`grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br ${tone} text-white`}><Icon className="h-7 w-7"/></div><div className="mt-8 flex items-start justify-between"><div><h3 className="text-2xl font-black">{name}</h3><p className="font-bold text-[#ff4f6d]">{handle}</p></div><ArrowUpRight className="transition group-hover:translate-x-1 group-hover:-translate-y-1"/></div><p className="mt-4 leading-7 text-slate-500">{text}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#0b4e80]">Follow along <CheckCircle2 className="h-4 w-4" /></span></a>)}</div></div></section>
 <section className="px-6 py-16 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] bg-[#ff4f6d] lg:grid-cols-[1fr_.9fr]"><div className="p-8 sm:p-12"><Play className="h-8 w-8"/><h2 className="mt-5 text-4xl font-black leading-tight">Have a question?<br />Send us a hello.</h2><p className="mt-4 text-rose-100">Our friendly team is only a message away.</p></div><form onSubmit={(e) => {e.preventDefault(); setSent(true);}} className="m-5 rounded-[1.5rem] bg-white p-6 text-slate-900 sm:m-8"><label className="text-sm font-bold">Your email</label><input required type="email" placeholder="you@example.com" className="mt-2 w-full rounded-xl bg-slate-100 px-4 py-3 outline-none ring-[#ff4f6d] focus:ring-2"/><button className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#071a32] px-4 py-3 font-bold text-white"><Send className="h-4 w-4" />{sent ? "Thanks — we’ll be in touch!" : "Send a message"}</button></form></div></section>
 </main>;
}
